development: &development
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: gtsapp_development
  pool: 5
  username: gtsapp
  password: gtsapp

test: &test
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: gtsapp_test
  pool: 5
  username: gtsapp
  password: gtsapp

production:
  <<: *development
#  adapter: sqlite3
#  database: db/production.sqlite3
#  pool: 5
#  timeout: 5000

cucumber:
  <<: *test