# encoding: utf-8
require 'spec_helper'
require 'shared/auth_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PostIndicesController do

  RSpec.configure do |c|
    c.include AuthHelper
  end

  before(:each) do
    authorize_user
  end

  # This should return the minimal set of attributes required to create a valid
  # PostIndex. As you add validations to PostIndex, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PostIndicesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all post_indices as @post_indices" do
      post_index = PostIndex.create! valid_attributes
      get :index, {}, valid_session
      assigns(:post_indices).should eq([post_index])
    end
  end

  describe "GET show" do
    it "assigns the requested post_index as @post_index" do
      post_index = PostIndex.create! valid_attributes
      get :show, {:id => post_index.to_param}, valid_session
      assigns(:post_index).should eq(post_index)
    end
  end

  describe "GET new" do
    it "assigns a new post_index as @post_index" do
      make_user_operator
      get :new, {}, valid_session
      assigns(:post_index).should be_a_new(PostIndex)
    end
  end

  describe "GET edit" do
    it "assigns the requested post_index as @post_index" do
      make_user_operator
      post_index = PostIndex.create! valid_attributes
      get :edit, {:id => post_index.to_param}, valid_session
      assigns(:post_index).should eq(post_index)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PostIndex" do
        make_user_operator
        expect {
          post :create, {:post_index => valid_attributes}, valid_session
        }.to change(PostIndex, :count).by(1)
      end

      it "assigns a newly created post_index as @post_index" do
        make_user_operator
        post :create, {:post_index => valid_attributes}, valid_session
        assigns(:post_index).should be_a(PostIndex)
        #noinspection RubyResolve
        assigns(:post_index).should be_persisted
      end

      it "redirects to the created post_index" do
        make_user_operator
        post :create, {:post_index => valid_attributes}, valid_session
        response.should redirect_to(PostIndex.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved post_index as @post_index" do
        make_user_operator
        # Trigger the behavior that occurs when invalid params are submitted
        PostIndex.any_instance.stub(:save).and_return(false)
        post :create, {:post_index => {}}, valid_session
        assigns(:post_index).should be_a_new(PostIndex)
      end

      it "re-renders the 'new' template" do
        make_user_operator
        # Trigger the behavior that occurs when invalid params are submitted
        PostIndex.any_instance.stub(:save).and_return(false)
        post :create, {:post_index => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested post_index" do
        make_user_operator
        post_index = PostIndex.create! valid_attributes
        # Assuming there are no other post_indices in the database, this
        # specifies that the PostIndex created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PostIndex.any_instance.should_receive(:update_attributes).with({:these.to_s => 'params'})
        put :update, {:id => post_index.to_param, :post_index => {:these => 'params'}}, valid_session
      end

      it "assigns the requested post_index as @post_index" do
        make_user_operator
        post_index = PostIndex.create! valid_attributes
        put :update, {:id => post_index.to_param, :post_index => valid_attributes}, valid_session
        assigns(:post_index).should eq(post_index)
      end

      it "redirects to the post_index" do
        make_user_operator
        post_index = PostIndex.create! valid_attributes
        put :update, {:id => post_index.to_param, :post_index => valid_attributes}, valid_session
        response.should redirect_to(post_index)
      end
    end

    describe "with invalid params" do
      it "assigns the post_index as @post_index" do
        make_user_operator
        post_index = PostIndex.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PostIndex.any_instance.stub(:save).and_return(false)
        put :update, {:id => post_index.to_param, :post_index => {}}, valid_session
        assigns(:post_index).should eq(post_index)
      end

      it "re-renders the 'edit' template" do
        make_user_operator
        post_index = PostIndex.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PostIndex.any_instance.stub(:save).and_return(false)
        put :update, {:id => post_index.to_param, :post_index => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested post_index" do
      make_user_operator
      post_index = PostIndex.create! valid_attributes
      expect {
        delete :destroy, {:id => post_index.to_param}, valid_session
      }.to change(PostIndex, :count).by(-1)
    end

    it "redirects to the post_indices list" do
      make_user_operator
      post_index = PostIndex.create! valid_attributes
      delete :destroy, {:id => post_index.to_param}, valid_session
      #noinspection RubyResolve
      response.should redirect_to(post_indices_url)
    end
  end

end
